### ISSUE TITLE
Error when running the CLI

### ISSUE THREAD

**Issue by karleg** [TheJacksonLaboratory/isopret#106]
I get the following error when trying to run the CLI, I checked it yesterday and it was fine so it may be something on my system:
16:09:38,496 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
16:09:38,496 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
16:09:38,497 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/Users/karleg/Downloads/isopret/isopret-cli/target/isopret-cli.jar!/BOOT-INF/classes!/logback.xml]
16:09:38,498 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
16:09:38,498 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/Users/karleg/Downloads/isopret/isopret-cli/target/isopret-cli.jar!/BOOT-INF/classes!/logback.xml]
16:09:38,498 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/Users/karleg/Downloads/isopret/isopret-cli/target/isopret-cli.jar!/BOOT-INF/lib/isopret-core-0.9.11.jar!/logback.xml]
16:09:38,516 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@14acaea5 - URL [jar:file:/Users/karleg/Downloads/isopret/isopret-cli/target/isopret-cli.jar!/BOOT-INF/classes!/logback.xml] is not of type file
16:09:38,571 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
16:09:38,572 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
16:09:38,579 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
16:09:38,585 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
16:09:38,641 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.monarchinitiative.phenol] to ERROR
16:09:38,641 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.springframework.boot] to ERROR
16:09:38,641 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
16:09:38,641 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
16:09:38,642 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
16:09:38,642 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@46d56d67 - Registering current configuration as safe fallback point

16:09:41.180 INFO  o.j.i.cli.command.IsopretCommand - Loaded Gene Ontology json file with 43705 terms.
16:09:41.182 INFO  o.j.i.cli.command.GoOverrepCommand - Loaded Gene Ontology with 43705 terms
java.lang.NullPointerException: Cannot invoke "java.util.Map.containsKey(Object)" because "geneSymbolAccessionListMap" is null
	at org.jax.isopret.core.hgnc.HgncParser.initHgncItems(HgncParser.java:125)
	at org.jax.isopret.core.hgnc.HgncParser.<init>(HgncParser.java:94)
	at org.jax.isopret.cli.command.GoOverrepCommand.call(GoOverrepCommand.java:71)
	at org.jax.isopret.cli.command.GoOverrepCommand.call(GoOverrepCommand.java:43)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.jax.isopret.cli.Main.main(Main.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)

**Comment by pnrobinson** [comment]
I can reproduce this bug with 
```
java -jar isopret-cli/target/isopret-cli.jar GO -b SRP279280_61.txt 
```
